/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.member.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.monitor.member.logic.dto.MemberDTO;
import co.edu.uniandes.csw.monitor.member.logic.api._IMemberLogicService;
import co.edu.uniandes.csw.monitor.member.persistence.api.IMemberPersistence;

public abstract class _MemberLogicService implements _IMemberLogicService {

	@Inject
	protected IMemberPersistence persistance;

	public MemberDTO createMember(MemberDTO member){
		return persistance.createMember( member); 
    }

	public List<MemberDTO> getMembers(){
		return persistance.getMembers(); 
	}

	public MemberDTO getMember(Long id){
		return persistance.getMember(id); 
	}

	public void deleteMember(Long id){
	    persistance.deleteMember(id); 
	}

	public void updateMember(MemberDTO member){
	    persistance.updateMember(member); 
	}	
}