/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.measureunit.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.monitor.measureunit.logic.dto.MeasureUnitDTO;
import co.edu.uniandes.csw.monitor.measureunit.persistence.api._IMeasureUnitPersistence;
import co.edu.uniandes.csw.monitor.measureunit.persistence.converter.MeasureUnitConverter;
import co.edu.uniandes.csw.monitor.measureunit.persistence.entity.MeasureUnitEntity;

public abstract class _MeasureUnitPersistence implements _IMeasureUnitPersistence {

  	@PersistenceContext(unitName="sportclubPU")
 
	protected EntityManager entityManager;
	
	public MeasureUnitDTO createMeasureUnit(MeasureUnitDTO measureUnit) {
		MeasureUnitEntity entity=MeasureUnitConverter.persistenceDTO2Entity(measureUnit);
		entityManager.persist(entity);
		return MeasureUnitConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<MeasureUnitDTO> getMeasureUnits() {
		Query q = entityManager.createQuery("select u from MeasureUnitEntity u");
		return MeasureUnitConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public MeasureUnitDTO getMeasureUnit(Long id) {
		return MeasureUnitConverter.entity2PersistenceDTO(entityManager.find(MeasureUnitEntity.class, id));
	}

	public void deleteMeasureUnit(Long id) {
		MeasureUnitEntity entity=entityManager.find(MeasureUnitEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateMeasureUnit(MeasureUnitDTO detail) {
		MeasureUnitEntity entity=entityManager.merge(MeasureUnitConverter.persistenceDTO2Entity(detail));
		MeasureUnitConverter.entity2PersistenceDTO(entity);
	}

}