/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.prize.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.monitor.prize.logic.dto.PrizeDTO;
import co.edu.uniandes.csw.monitor.prize.persistence.api._IPrizePersistence;
import co.edu.uniandes.csw.monitor.prize.persistence.converter.PrizeConverter;
import co.edu.uniandes.csw.monitor.prize.persistence.entity.PrizeEntity;

public abstract class _PrizePersistence implements _IPrizePersistence {

  	@PersistenceContext(unitName="sportclubPU")
 
	protected EntityManager entityManager;
	
	public PrizeDTO createPrize(PrizeDTO prize) {
		PrizeEntity entity=PrizeConverter.persistenceDTO2Entity(prize);
		entityManager.persist(entity);
		return PrizeConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<PrizeDTO> getPrizes() {
		Query q = entityManager.createQuery("select u from PrizeEntity u");
		return PrizeConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public PrizeDTO getPrize(Long id) {
		return PrizeConverter.entity2PersistenceDTO(entityManager.find(PrizeEntity.class, id));
	}

	public void deletePrize(Long id) {
		PrizeEntity entity=entityManager.find(PrizeEntity.class, id);
		entityManager.remove(entity);
	}

	public void updatePrize(PrizeDTO detail) {
		PrizeEntity entity=entityManager.merge(PrizeConverter.persistenceDTO2Entity(detail));
		PrizeConverter.entity2PersistenceDTO(entity);
	}

}