/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_addressModel'], function() {
    App.Model.AddressModel = App.Model._AddressModel.extend({

 	validate: function(attrs,options){
            var validationMessage = "";
            
            if(!attrs.street){
               validationMessage="Debe llenar todos los campos! falta el campo street";
            }
             //alert("1");
            if(!attrs.aveneu){
                validationMessage="Debe llenar todos los campos! falta el campo aveneu";
            }
             //alert("2");
            if(!attrs.cityId){
                validationMessage="Debe llenar todos los campos! falta el capo cityId";
            }
             //alert("3");
             var calle = parseInt( attrs.street );
            // alert(typeof calle);
             var avenida =parseInt( attrs.aveneu );
             
             if(attrs.street.length>3){
                validationMessage="Street no puede tener mas de 3 digitos";
            }
             //alert("5");
            if(attrs.aveneu.length>3){
                validationMessage="Aveneu no puede tener mas de 3 digitos";
            }
             //alert("6");
            if(isNaN(calle)){
               validationMessage="Street deberia ser un numero!";
            }
            if(isNaN(avenida)){
               validationMessage="Aveneu deberia ser un numero!";
            }
             //alert(typeof  attrs.street);
            
            
            
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.AddressList = App.Model._AddressList.extend({
        model: App.Model.AddressModel
    });

    return  App.Model.AddressModel;

});