/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.member.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.monitor.member.logic.dto.MemberDTO;
import co.edu.uniandes.csw.monitor.member.persistence.api._IMemberPersistence;
import co.edu.uniandes.csw.monitor.member.persistence.converter.MemberConverter;
import co.edu.uniandes.csw.monitor.member.persistence.entity.MemberEntity;

public abstract class _MemberPersistence implements _IMemberPersistence {

  	@PersistenceContext(unitName="sportclubPU")
 
	protected EntityManager entityManager;
	
	public MemberDTO createMember(MemberDTO member) {
		MemberEntity entity=MemberConverter.persistenceDTO2Entity(member);
		entityManager.persist(entity);
		return MemberConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<MemberDTO> getMembers() {
		Query q = entityManager.createQuery("select u from MemberEntity u");
		return MemberConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public MemberDTO getMember(Long id) {
		return MemberConverter.entity2PersistenceDTO(entityManager.find(MemberEntity.class, id));
	}

	public void deleteMember(Long id) {
		MemberEntity entity=entityManager.find(MemberEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateMember(MemberDTO detail) {
		MemberEntity entity=entityManager.merge(MemberConverter.persistenceDTO2Entity(detail));
		MemberConverter.entity2PersistenceDTO(entity);
	}

}