/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.member.master.persistence;
import co.edu.uniandes.csw.monitor.address.logic.dto.AddressDTO;
import co.edu.uniandes.csw.monitor.member.master.persistence.entity.MemberaddressesEntity;
import co.edu.uniandes.csw.monitor.address.persistence.converter.AddressConverter;
import co.edu.uniandes.csw.monitor.member.logic.dto.MemberDTO;
import co.edu.uniandes.csw.monitor.member.master.persistence.entity.MemberrelativesEntity;
import co.edu.uniandes.csw.monitor.member.persistence.converter.MemberConverter;
import co.edu.uniandes.csw.monitor.sport.logic.dto.SportDTO;
import co.edu.uniandes.csw.monitor.member.master.persistence.entity.MembersportsEntity;
import co.edu.uniandes.csw.monitor.sport.persistence.converter.SportConverter;
import co.edu.uniandes.csw.monitor.member.logic.dto.MemberDTO;
import co.edu.uniandes.csw.monitor.member.master.logic.dto.MemberMasterDTO;
import co.edu.uniandes.csw.monitor.member.master.persistence.api._IMemberMasterPersistence;
import co.edu.uniandes.csw.monitor.member.persistence.api.IMemberPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _MemberMasterPersistence implements _IMemberMasterPersistence {

  	@PersistenceContext(unitName="sportclubPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IMemberPersistence memberPersistence;  

    public MemberMasterDTO getMember(Long memberId) {
        MemberMasterDTO memberMasterDTO = new MemberMasterDTO();
        MemberDTO member = memberPersistence.getMember(memberId);
        memberMasterDTO.setMemberEntity(member);
        memberMasterDTO.setListaddresses(getMemberaddressesEntityList(memberId));
        memberMasterDTO.setListrelatives(getMemberrelativesEntityList(memberId));
        memberMasterDTO.setListsports(getMembersportsEntityList(memberId));
        return memberMasterDTO;
    }

    public MemberaddressesEntity createMemberaddressesEntity(MemberaddressesEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteMemberaddressesEntity(Long memberId, Long addressesId) {
        Query q = entityManager.createNamedQuery("MemberaddressesEntity.deleteMemberaddressesEntity");
        q.setParameter("memberId", memberId);
        q.setParameter("addressesId", addressesId);
        q.executeUpdate();
    }

    public List<AddressDTO> getMemberaddressesEntityList(Long memberId) {
        ArrayList<AddressDTO> resp = new ArrayList<AddressDTO>();
        Query q = entityManager.createNamedQuery("MemberaddressesEntity.getByMasterId");
        q.setParameter("memberId",memberId);
        List<MemberaddressesEntity> qResult =  q.getResultList();
        for (MemberaddressesEntity entity : qResult) { 
            if(entity.getAddressesIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(AddressConverter.entity2PersistenceDTO(entity.getAddressesIdEntity()));
        }
        return resp;
    }
    public MemberrelativesEntity createMemberrelativesEntity(MemberrelativesEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteMemberrelativesEntity(Long memberId, Long relativesId) {
        Query q = entityManager.createNamedQuery("MemberrelativesEntity.deleteMemberrelativesEntity");
        q.setParameter("memberId", memberId);
        q.setParameter("relativesId", relativesId);
        q.executeUpdate();
    }

    public List<MemberDTO> getMemberrelativesEntityList(Long memberId) {
        ArrayList<MemberDTO> resp = new ArrayList<MemberDTO>();
        Query q = entityManager.createNamedQuery("MemberrelativesEntity.getByMasterId");
        q.setParameter("memberId",memberId);
        List<MemberrelativesEntity> qResult =  q.getResultList();
        for (MemberrelativesEntity entity : qResult) { 
            if(entity.getRelativesIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(MemberConverter.entity2PersistenceDTO(entity.getRelativesIdEntity()));
        }
        return resp;
    }
    public MembersportsEntity createMembersportsEntity(MembersportsEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteMembersportsEntity(Long memberId, Long sportsId) {
        Query q = entityManager.createNamedQuery("MembersportsEntity.deleteMembersportsEntity");
        q.setParameter("memberId", memberId);
        q.setParameter("sportsId", sportsId);
        q.executeUpdate();
    }

    public List<SportDTO> getMembersportsEntityList(Long memberId) {
        ArrayList<SportDTO> resp = new ArrayList<SportDTO>();
        Query q = entityManager.createNamedQuery("MembersportsEntity.getByMasterId");
        q.setParameter("memberId",memberId);
        List<MembersportsEntity> qResult =  q.getResultList();
        for (MembersportsEntity entity : qResult) { 
            if(entity.getSportsIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(SportConverter.entity2PersistenceDTO(entity.getSportsIdEntity()));
        }
        return resp;
    }

}
