/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.city.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.monitor.city.logic.dto.CityDTO;
import co.edu.uniandes.csw.monitor.city.persistence.api._ICityPersistence;
import co.edu.uniandes.csw.monitor.city.persistence.converter.CityConverter;
import co.edu.uniandes.csw.monitor.city.persistence.entity.CityEntity;

public abstract class _CityPersistence implements _ICityPersistence {

  	@PersistenceContext(unitName="sportclubPU")
 
	protected EntityManager entityManager;
	
	public CityDTO createCity(CityDTO city) {
		CityEntity entity=CityConverter.persistenceDTO2Entity(city);
		entityManager.persist(entity);
		return CityConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<CityDTO> getCitys() {
		Query q = entityManager.createQuery("select u from CityEntity u");
		return CityConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public CityDTO getCity(Long id) {
		return CityConverter.entity2PersistenceDTO(entityManager.find(CityEntity.class, id));
	}

	public void deleteCity(Long id) {
		CityEntity entity=entityManager.find(CityEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateCity(CityDTO detail) {
		CityEntity entity=entityManager.merge(CityConverter.persistenceDTO2Entity(detail));
		CityConverter.entity2PersistenceDTO(entity);
	}

}