/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.member.master.logic.dto;

import co.edu.uniandes.csw.monitor.address.logic.dto.AddressDTO;
import co.edu.uniandes.csw.monitor.member.logic.dto.MemberDTO;
import co.edu.uniandes.csw.monitor.sport.logic.dto.SportDTO;
import co.edu.uniandes.csw.monitor.member.logic.dto.MemberDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _MemberMasterDTO {

 
    protected MemberDTO memberEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public MemberDTO getMemberEntity() {
        return memberEntity;
    }

    public void setMemberEntity(MemberDTO memberEntity) {
        this.memberEntity = memberEntity;
    }
    
    public List<AddressDTO> createaddresses;
    public List<AddressDTO> updateaddresses;
    public List<AddressDTO> deleteaddresses;
    public List<AddressDTO> listaddresses;	
    public List<MemberDTO> createrelatives;
    public List<MemberDTO> updaterelatives;
    public List<MemberDTO> deleterelatives;
    public List<MemberDTO> listrelatives;	
    public List<SportDTO> createsports;
    public List<SportDTO> updatesports;
    public List<SportDTO> deletesports;
    public List<SportDTO> listsports;	
	
	
	
    public List<AddressDTO> getCreateaddresses(){ return createaddresses; };
    public void setCreateaddresses(List<AddressDTO> createaddresses){ this.createaddresses=createaddresses; };
    public List<AddressDTO> getUpdateaddresses(){ return updateaddresses; };
    public void setUpdateaddresses(List<AddressDTO> updateaddresses){ this.updateaddresses=updateaddresses; };
    public List<AddressDTO> getDeleteaddresses(){ return deleteaddresses; };
    public void setDeleteaddresses(List<AddressDTO> deleteaddresses){ this.deleteaddresses=deleteaddresses; };
    public List<AddressDTO> getListaddresses(){ return listaddresses; };
    public void setListaddresses(List<AddressDTO> listaddresses){ this.listaddresses=listaddresses; };	
    public List<MemberDTO> getCreaterelatives(){ return createrelatives; };
    public void setCreaterelatives(List<MemberDTO> createrelatives){ this.createrelatives=createrelatives; };
    public List<MemberDTO> getUpdaterelatives(){ return updaterelatives; };
    public void setUpdaterelatives(List<MemberDTO> updaterelatives){ this.updaterelatives=updaterelatives; };
    public List<MemberDTO> getDeleterelatives(){ return deleterelatives; };
    public void setDeleterelatives(List<MemberDTO> deleterelatives){ this.deleterelatives=deleterelatives; };
    public List<MemberDTO> getListrelatives(){ return listrelatives; };
    public void setListrelatives(List<MemberDTO> listrelatives){ this.listrelatives=listrelatives; };	
    public List<SportDTO> getCreatesports(){ return createsports; };
    public void setCreatesports(List<SportDTO> createsports){ this.createsports=createsports; };
    public List<SportDTO> getUpdatesports(){ return updatesports; };
    public void setUpdatesports(List<SportDTO> updatesports){ this.updatesports=updatesports; };
    public List<SportDTO> getDeletesports(){ return deletesports; };
    public void setDeletesports(List<SportDTO> deletesports){ this.deletesports=deletesports; };
    public List<SportDTO> getListsports(){ return listsports; };
    public void setListsports(List<SportDTO> listsports){ this.listsports=listsports; };	
	
	
}

