/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.member.master.persistence.entity;

import co.edu.uniandes.csw.monitor.member.persistence.entity.MemberEntity;
import co.edu.uniandes.csw.monitor.member.persistence.entity.MemberEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(MemberrelativesEntityId.class)
@NamedQueries({
    @NamedQuery(name = "MemberrelativesEntity.getByMasterId", query = "SELECT  u FROM MemberrelativesEntity u WHERE u.memberId=:memberId"),
    @NamedQuery(name = "MemberrelativesEntity.deleteMemberrelativesEntity", query = "DELETE FROM MemberrelativesEntity u WHERE u.memberId=:memberId and  u.relativesId=:relativesId")
})
public class MemberrelativesEntity implements Serializable {

    @Id
    @Column(name = "memberId")
    private Long memberId;
    @Id
    @Column(name = "relativesId")
    private Long relativesId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "memberId", referencedColumnName = "id")
    @JoinFetch
    private MemberEntity memberIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "relativesId", referencedColumnName = "id")
    @JoinFetch
    private MemberEntity relativesIdEntity; 

    public MemberrelativesEntity() {
    }

    public MemberrelativesEntity(Long memberId, Long relativesId) {
        this.memberId =memberId;
        this.relativesId = relativesId;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public Long getRelativesId() {
        return relativesId;
    }

    public void setRelativesId(Long relativesId) {
        this.relativesId = relativesId;
    }

    public MemberEntity getMemberIdEntity() {
        return memberIdEntity;
    }

    public void setMemberIdEntity(MemberEntity memberIdEntity) {
        this.memberIdEntity = memberIdEntity;
    }

    public MemberEntity getRelativesIdEntity() {
        return relativesIdEntity;
    }

    public void setRelativesIdEntity(MemberEntity relativesIdEntity) {
        this.relativesIdEntity = relativesIdEntity;
    }

}
