/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.monitor.referee.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.monitor.referee.logic.dto.RefereeDTO;
import co.edu.uniandes.csw.monitor.referee.persistence.entity.RefereeEntity;

public abstract class _RefereeConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static RefereeDTO entity2PersistenceDTO(RefereeEntity entity){
		if (entity != null) {
			RefereeDTO dto = new RefereeDTO();
					dto.setAgeOfExpirience(entity.getAgeOfExpirience());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setFirstName(entity.getFirstName());
					dto.setLastName(entity.getLastName());
 
			    if(entity.getBirthDate() != null){
					dto.setBirthDate(DATE_FORMAT.format(entity.getBirthDate()));
				}	
					dto.setEnable(entity.getEnable());
					dto.setDocNumber(entity.getDocNumber());
			return dto;
		}else{
			return null;
		}
	}
	
	public static RefereeEntity persistenceDTO2Entity(RefereeDTO dto){
		if(dto!=null){
			RefereeEntity entity=new RefereeEntity();
					entity.setAgeOfExpirience(dto.getAgeOfExpirience());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setFirstName(dto.getFirstName());
			
					entity.setLastName(dto.getLastName());
			
 
			      try{ 
			        if(dto.getBirthDate() != null){
						entity.setBirthDate(DATE_FORMAT.parse(dto.getBirthDate()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_RefereeConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setEnable(dto.getEnable());
			
					entity.setDocNumber(dto.getDocNumber());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<RefereeDTO> entity2PersistenceDTOList(List<RefereeEntity> entities){
		List<RefereeDTO> dtos=new ArrayList<RefereeDTO>();
		for(RefereeEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<RefereeEntity> persistenceDTO2EntityList(List<RefereeDTO> dtos){
		List<RefereeEntity> entities=new ArrayList<RefereeEntity>();
		for(RefereeDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}